### ISSUE TITLE
update promotional materials)

### ISSUE THREAD

**Issue by hcorona-zz** [hcorona/WWC-recsys#20]
An example of an email invitation and eventbrite invitation

"" 
No, we’re not reading your mind.

Ever notice how so much of your online experience is curated to you - recommended outfits on Zalando, suggested songs or books. In this interactive workshop, we will introduce and practice the most important concepts about recommender systems, the force behind the personalized experience.

By the end of the workshop, you will be able to build your own recommender system and discuss the outcomes with the help of our mentors, all in a very informal and interactive way. If you’ve got basic Python knowledge, you’re a great fit for this workshop. Bring along a friend and code together!

Schedule:
12.30 - 1.15 pm: Lunch
1.15 - 1.45 pm: 101 Recommender Systems
1.45 - 3.15 pm: Hacking Recommender Systems!
3.15 - 3.45 pm: Wrap Up discussion
""""

**Comment by kevllino** [comment]
Looks good @hcorona ! I think it would be useful to include a requirement section as a reminder, based on [this](https://github.com/hcorona/recsys-101-workshop/blob/master/docs/instructions.md).

**Comment by hcorona-zz** [comment]
done, : )
