### ISSUE TITLE
Update of instructions 

### ISSUE THREAD

**Issue by kevllino** [hcorona/WWC-recsys#22]
Instructions are very clean, I think they can be better: 

1. Can you add an instruction to install `matplotlib` in the [instructions](https://github.com/hcorona/recsys-101-workshop/blob/master/docs/instructions.md#installing-and-configuring-python) and `setup.py`? As it's not a package that everyone has

2. Can you add a `How to run` section after [ Before the session](https://github.com/hcorona/recsys-101-workshop/blob/master/docs/instructions.md#installing-and-configuring-python)? to make it extra clear what needs to be done to run your notebooks in order.

What do you think of the above? Looks awesome otherwise, I'll continue reviewing the rest.

**Comment by hcorona-zz** [comment]
@kevllino : the changes have been added into #24 , could you take a look and approve the changes?

**Comment by hcorona-zz** [comment]
solved
